name: Android Build Dev APK

on: [push]

defaults:
  run:
    working-directory: ./app
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
      - run: npm install yarn -g
      - run: yarn install
      - name: Build
        run: yarn build:native:android
      - name: Build debug APK
        working-directory: ./android
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./android/app/build/outputs/apk/debug/app-debug.apk
