name: ESP IDF

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
    - name: Cache build
      id: cache-build
      uses: actions/cache@v1
      with:
        path: ${{github.workspace}}/targets/esp32/build
        key: ${{ runner.os }}-esp32-build2
    - name: Build the firmware
      run: |
        cd web
        npm install
        npm run build
        cd ..
        mkdir -p targets/esp32/app/spiffs
        cp -r web/dist/. targets/esp32/app/spiffs/
        echo ${{github.ref_name}} > targets/esp32/app/spiffs/scripts-version
        echo ${{github.ref_name}} > euphonium/scripts/scripts-version
        docker run --rm -v $PWD:/project --env EUPH_VER=${{github.ref_name}} -w /project espressif/idf:release-v4.4 /bin/bash -c "apt-get update && \
          wget https://dl.google.com/go/go1.15.2.linux-amd64.tar.gz && tar -xvf go1.15.2.linux-amd64.tar.gz && \
          mv go /usr/local && \
          export GOROOT=/usr/local/go && \
          export PATH=\$PATH:\$GOPATH/bin:\$GOROOT/bin && \
          export GOPATH=\$HOME && \
          apt-get install --no-install-recommends --assume-yes protobuf-compiler && \
          python3 -m pip install --upgrade pip setuptools wheel && \
          pip3 install protobuf grpcio-tools && cd targets/esp32 && sh generate_full_build.sh"
        ls -la targets/esp32/build
        cat euphonium/scripts/scripts-version
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Firmware
        path: |
          targets/esp32/*.tar.gz
          targets/esp32/ota_checksum.txt
          targets/esp32/scripts.tar
          targets/esp32/scripts_checksum.txt
          targets/esp32/ota.bin
          
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "build/euphonium-esp32.bin, targets/esp32/euphonium-${{github.ref_name}}.tar.gz, targets/esp32/ota_checksum.txt, targets/esp32/scripts.tar, targets/esp32/scripts_checksum.txt, targets/esp32/ota.bin"

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      # Only runs if all of the files exists
      run: echo All files exists!
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          targets/esp32/euphonium-${{github.ref_name}}.tar.gz
          targets/esp32/ota_checksum.txt
          targets/esp32/scripts.tar
          targets/esp32/scripts_checksum.txt
          targets/esp32/ota.bin
